# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatFramework

  pod 'JitsiMeetSDK', '5.1.0'
#  pod 'Starscream', '~> 4.0.0'
  
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
#  pod 'GoogleWebRTC'
#  pod 'ChatViewController'
  pod 'Kingfisher'
  pod 'SwiftyJSON'
  pod 'NotificationBannerSwift', '~> 3.0.0'
  pod 'PlaceholderUITextView'

end
